name: jellydesk
description: A modern Flutter client for Jellyfin with multi-server, Quick Connect, Cast/AirPlay, and desktop support.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  go_router: ^14.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  cast: ^2.1.0
  flutter_to_airplay: ^2.0.5
  cached_network_image: ^3.3.1
  uuid: ^4.4.0  
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1  

dependency_overrides:
  bonsoir: 5.1.11
  bonsoir_platform_interface: 5.1.3

flutter_launcher_icons:
  image_path: assets/icon.png

  # Plattformen
  android: true
  ios: true

  macos:
    generate: true
    image_path: assets/icon.png

  windows:
    generate: true
    image_path: assets/icon.png
    icon_size: 256

flutter_native_splash:
  color: "#000000"
  image: assets/icon_white.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#000000"
    image: assets/icon_white.png


flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/icon_white.png
    - assets/logo.png
    - assets/logo_white.png
    - assets/logo_grad.png