name: jellydesk
description: A modern Flutter client for Jellyfin with multi-server, Quick Connect, Cast/AirPlay, and desktop support.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  go_router: ^14.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  # Playback
  video_player: ^2.9.1
  # Cast (Chromecast)
  cast: ^2.1.0
  # AirPlay (iOS only plugin; safe to keep as dependency)
  flutter_to_airplay: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  hive_generator: ^2.0.1

dependency_overrides:
  # Fix für API-Änderungen in bonsoir 6.x, die mit cast 2.1.0 kollidieren
  bonsoir: 5.1.11
  bonsoir_platform_interface: 5.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
