// GENERATED BY HAND for portability in this demo.

part of 'models.dart';

class ServerProfileAdapter extends TypeAdapter<ServerProfile> {
  @override
  final int typeId = 11;

  @override
  ServerProfile read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return ServerProfile(
      name: fields[0] as String,
      baseUrl: fields[1] as String,
      accessToken: fields[2] as String?,
      userId: fields[3] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, ServerProfile obj) {
    writer
      ..writeByte(4)
      ..writeByte(0)
      ..write(obj.name)
      ..writeByte(1)
      ..write(obj.baseUrl)
      ..writeByte(2)
      ..write(obj.accessToken)
      ..writeByte(3)
      ..write(obj.userId);
  }
}
